webhook_cleanup_job:
  class: "WebhookCleanupJob"
  queue: low
  cron: "*/5 * * * *"

eta_batch_recalculation_job:
  class: "EtaBatchRecalculationJob"
  queue: low
  cron: "*/15 * * * *"

purge_expired_tokens_job:
  class: "PurgeExpiredTokensJob"
  queue: low
  cron: "0 2 * * *"

archive_old_location_pings_job:
  class: "ArchiveOldLocationPingsJob"
  queue: low
  cron: "0 3 * * *"

scheduled_report_job:
  class: "ScheduledReportJob"
  queue: low
  cron: "0 6 * * 1"

monthly_expense_summary_job:
  class: "MonthlyExpenseSummaryJob"
  queue: low
  cron: "0 7 1 * *"

check_maintenance_due_job:
  class: "Maintenance::CheckDueJob"
  queue: low
  cron: "0 * * * *"

check_vehicle_document_expiry_job:
  class: "Maintenance::CheckDocumentExpiryJob"
  queue: low
  cron: "0 5 * * *"

process_escalations_job:
  class: "Notifications::ProcessEscalationsJob"
  queue: default
  cron: "*/5 * * * *"

fuel_baseline_recalculation_job:
  class: "Fuel::FuelBaselineRecalculationJob"
  queue: low
  cron: "0 4 * * 1"

fuel_anomaly_digest_job:
  class: "Fuel::FuelAnomalyDigestJob"
  queue: low
  cron: "0 8 * * *"

calculate_weekly_driver_scores_job:
  class: "Driver::CalculateWeeklyDriverScoresJob"
  queue: default
  cron: "0 2 * * 1"

calculate_monthly_driver_scores_job:
  class: "Driver::CalculateMonthlyDriverScoresJob"
  queue: default
  cron: "0 3 1 * *"

check_driver_document_expiry_job:
  class: "Driver::CheckDriverDocumentExpiryJob"
  queue: default
  cron: "0 7 * * *"

driver_score_notification_job:
  class: "Driver::DriverScoreNotificationJob"
  queue: default
  cron: "0 8 * * 1"
