:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>
:queues:
  - [critical, 5]
  - [default, 3]
  - [mailers, 2]
  - [low, 1]

production:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 10) %>

development:
  :concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY", 5) %>
